manala:
  repository: "https://github.com/loic-roux-404/manala-recipes.git" 
  recipe: ops.playbook


gitignore: |
    files/data/*
    files/letsencrypt/*
    vault_pass.sh
    files/letsencrypt/*

ansible: 
  auto_tag: false
  cfg_lines:
      vault_password_file: ./vault_pass.sh
  internal_roles: true
  inventory: ./inventory
  privilege_escalation:
      become: true
      become_ask_pass: false
      become_method: sudo
      become_user: root

vagrant: 
  project_name: nginx-reverse-proxy
  box: loic-roux-404/deb64-buster
  box_update: false
  box_version: null
  vb_guest_update: false
  domain: loicroux.com
  git: 
    org: loic-roux-404
    provider: github.com
  paths: 
    guest: /vagrant
    host: ./
    web: ""
  network: 
    dns: true
    fix_routing: true
    ip: null
    ports: []
    ssl:
        cert: null
        path: /etc/ssl
    type: public 
  ansible: 
    disabled: true
    inventory: ./inventory
    playbook: ""
    playbook_version: master
    sub_playbook: site.yml
    type: local
    vars: {}
  fs: 
    opts:
        disabled: true
        ignored:
            - /**/.DS_Store
            - .git
            - .vagrant
            - .idea/
            - .vscode/
        rsync_auto: true
        smb_password: null
        smb_username: null
    type: rsync
  provider:  
    opts:
        cpus: "2"
        memory: "1024"
        natdnshostresolver1: "on"
    type: virtualbox
