---
###################
# Launch this playbook on your host
# It need a chrome browser with github logged
###################
- hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  become_user: root
  roles:
    - { role: role-github-app, tags: [github-app] }
