- hosts: nginx_instances
  gather_facts: true
  become: yes
  become_user: root
  tags: [revproxy]
  vars:
    tag: rev_proxy_admin
  tasks:
    - name: pip deps
      pip:
        name: docker
    - name: Copy config
      tags: [cnf]
      copy:
        src: "{{ item }}"
        dest: $HOME/
        owner: root
        group: root
        mode: '0500'
      loop:
        - nginx/Dockerfile
        - nginx/config.json

    - name: restart docker
      service:
        name: docker
        state: restarted
        enabled: true

    - name: build container
      tags: [build]
      community.general.docker_image:
        build:
          path: "$HOME/"
          pull: no
        name: "{{ tag }}"
        tag: latest
        force_absent: yes
        force_source: yes
        source: build
        state: present

    - name: up docker container
      tags: [build, deploy]
      community.general.docker_container:
        name: "{{ tag }}"
        image: "{{ tag }}:latest"
        state: started
        restart_policy: always
        ports:
          # Public HTTP Port:
          - '80:80'
          # Public HTTPS Port:
          - '443:443'
          # Admin Web Port:
          - '81:81'
        healthcheck:
          # Check if nginx server is healthy by curl'ing the server.
          # If this fails or timeouts, the healthcheck fails.
          test: ["CMD", "curl", "--fail", "http://loicroux.com"]
          interval: 5m30s
          timeout: 10s
          retries: 3
          start_period: 30s
        env:
        # Uncomment this if IPv6 is not enabled on your host
          DISABLE_IPV6: 'true'
        volumes:
        # Make sure this config.json file exists as per instructions above:
          - ./config.json:/app/config/production.json
          - ./data:/data
          - ./letsencrypt:/etc/letsencrypt
