---
# Required ansible collections
roles:
  # Github roles
  - name: role-users
    src: weareinteractive.users
  - name: role-basics
    src: ssh://git@github.com/loic-roux-404/role-basics.git
    version: "master"
    scm: git
  - name: role-dns
    src: ssh://git@github.com/mrlesmithjr/ansible-dnsmasq.git
    version: "master"
    scm: git
  - name: role-tools
    version: master
    src: ssh://git@github.com/loic-roux-404/role-tools.git
  - name: role-swarmlet
    version: master
    src: ssh://git@github.com/loic-roux-404/role-swarmlet.git
    scm: git
  - name: role-github-app
    version: master
    src: ssh://git@github.com/loic-roux-404/role-github-app.git
    scm: git
  - name: role-upgrade
    version: master
    src: ssh://git@github.com/loic-roux-404/role-upgrade.git
    scm: git
  - name: role-shell
    version: master
    src: ssh://git@github.com/loic-roux-404/role-shell.git
    scm: git
  # External requirements
  - name: role-logrotate
    src: arillso.logrotate
  - name: role-firewall
    src: geerlingguy.firewall
  - name: role-security
    src: geerlingguy.firewall
  - name: role-sudo
    src: weareinteractive.sudo
    version: master
  - name: role-docker
    src: nickjj.docker
  - name: role-prometheus
    src: cloudalchemy.prometheus
# replace zsh by role: gantsign.oh-my-zsh

collections:
  - name: community.general
  - name: community.docker
  - name: ansible.netcommon
  - name: ansible.posix
  - name: community.crypto.openssh_keypair
