---
# Required ansible collections
roles:
  # Github roles
  - name: role-basics
    src: ssh://git@github.com/loic-roux-404/role-basics.git
    version: "configs"
    scm: git
  - name: role-dns
    src: ssh://git@github.com/loic-roux-404/role-dns.git
    version: "master"
    scm: git
  - name: role-traefik
    version: master
    src: ssh://git@github.com/loic-roux-404/role-traefik.git
    scm: git
  # External requirements
  - name: role-logrotate
    src: arillso.logrotate
  - name: role-firewall
    src: geerlingguy.firewall
    version: 2.5.0
  - name: role-security
    src: geerlingguy.security
    version: 2.0.1
  - name: role-docker
    src: nickjj.docker
    version: v2.0.0
  - name: role-consul-template
    src: griggheo.consul-template
    version: 1.2.4
  - name: role-nomad
    src: brianshumate.nomad
    version: v1.9.5
  - name: role-consul
    src: ssh://git@github.com/ansible-community/ansible-consul.git
    version: v2.6.1
    scm: git
  - name: role-vault
    version: v2.5.4
    src: ssh://git@github.com/ansible-community/ansible-vault.git
    scm: git
  - name: role-prometheus
    src: ssh://git@github.com/cloudalchemy/ansible-prometheus.git
    scm: git

collections:
  - name: community.general
