---
# Required ansible collections
roles:
  # Github roles
  - name: role-users
    src: weareinteractive.users
    version: 1.17.0
  - name: role-basics
    src: ssh://git@github.com/loic-roux-404/role-basics.git
    version: "configs"
    scm: git
  - name: role-dns
    src: ssh://git@github.com/loic-roux-404/role-dns.git
    version: "master"
    scm: git
  - name: role-tools
    version: master
    src: ssh://git@github.com/loic-roux-404/role-tools.git
    scm: git
  # External requirements
  - name: role-logrotate
    src: arillso.logrotate
  - name: role-firewall
    src: geerlingguy.firewall
    version: 2.5.0
  - name: role-security
    src: ssh://git@github.com/loic-roux-404/role-security.git
    scm: git
    version: master
  - name: role-docker
    src: nickjj.docker
    version: v2.1.0
  # - name: role-consul-template
  #   src: griggheo.consul-template
  #   version: 1.2.4
  - name: role-prometheus
    src: ssh://git@github.com/cloudalchemy/ansible-prometheus.git
    scm: git
# replace zsh by role: gantsign.oh-my-zsh

collections:
  - name: community.general
  - name: ansible.netcommon
  - name: ansible.posix
