---
# First playbook needed to be applied
- hosts: security
  gather_facts: True
  become: True
  become_user: root
  pre_tasks:
  roles:
    - role: role-upgrade
      tags: [system]
      vars: { apt_install: [sudo, zsh, acl] }
    - role: role-users
      tags: [system, users]
    - role: role-sudo
      tags: [system]
    - role: role-security
      tags: [network]
    - role: role-firewall
      tags: [network]
    - role: role-dns
      tags: [network]
    - role: role-basics
      tags: [system, network, users]
