---
# First playbook needed to be applied
- hosts: security
  gather_facts: True
  become: True
  become_user: root
  pre_tasks:
    - name: Install required playbook packages
      ansible.builtin.package:
        name:
          - sudo
          - sshpass
          - zsh
        state: latest
  roles:
    - role: role-upgrade
      tags: [system, security]
    - role: role-users
      tags: [system, security]
    - role: role-security
      tags: [network-security, security]
    - role: role-firewall
      tags: [network-security, security]
