---
# First playbook needed to be applied
- hosts: security
  gather_facts: True
  become: True
  become_user: root
  pre_tasks:
    - name: Install required playbook packages
      ansible.builtin.package:
        name:
          - sudo
          - zsh
          - acl # avoid perms issue with ansible
        state: latest
  roles:
    - role: role-upgrade
      tags: [system]
    - role: role-users
      tags: [system, users]
    - role: role-basics
      tags: [system, users]
    - role: role-sudo
      tags: [system]
    - role: role-security
      tags: [network]
    - role: role-firewall
      tags: [network]
