---
# First playbook needed to be applied
- hosts: security
  gather_facts: True
  become: True
  become_user: root
  pre_tasks:
    - name: Upgrade debian
      ansible.builtin.apt:
        upgrade: safe
      when: ansible_os_family == 'Debian'

    - name: Install required playbook packages
      ansible.builtin.package:
        name:
          - sudo
          - sshpass
          - zsh
        state: latest
  roles:
    - role: role-users
    - role: role-security
    - role: role-firewall
