---
- hosts: security
  gather_facts: true
  become: yes
  pre_tasks:
    # TODO check if we wan use that in env and remove users here
    - package:
        name:
          - sudo
          - zsh
          - sshpass
        state: latest
  roles:
    - role: role-users
    - role: role-security
    - role: role-firewall
