---
# First playbook needed to be applied
- hosts: security
  gather_facts: True
  become: True
  become_user: root
  pre_tasks:
    - package:
        name:
          - sudo
          - zsh
          - sshpass
        state: latest
  roles:
    - role: role-users
    - role: role-security
    - role: role-firewall
