---
- hosts: stack
  gather_facts: true
  become: yes
  roles:
    - { role: role-dns,  tags: ['dns'] }
    - { role: role-docker, tags: ['dns','docker'] }
    - { role: role-nomad, tags: ['dns', 'docker', 'nomad'] }
    - role: role-logrotate
