---
- hosts: docker_instances
  gather_facts: true
  become: yes
  become_user: root
  roles:
    - { role: role-docker, tags: [stack] }
    - { role: role-nomad, tags: [stack] }
    - { role: role-logrotate, tags: [stack] }

- hosts: consul_instances
  become: true
  become_user: root
  roles:
    - { role: role-dns, tags: [discovery] }
    - { role: role-consul, tags: [discovery] }

- hosts: vault_instances
  gather_facts: true
  become: true
  become_user: root
  roles:
    - role: role-vault
