---
- hosts: stack
  gather_facts: true
  become: yes
  roles:
    - { role: role-dns,  tags: ['dns'] }
    - { role: role-docker, tags: ['docker'] }
    - { role: role-nomad, tags: ['nomad'] }
    - role: role-logrotate
