---
- hosts: stack
  gather_facts: true
  become: yes
  roles:
    - { role: role-stack,  tags: ['stack'] }
    - { role: role-docker, tags: ['stack','docker'] }
    - { role: role-nomad, tags: ['stack', 'docker', 'nomad'] }
    - role: role-logrotate

# - hosts: traefiks
#   become: true
#   become_user: root
#   ignore_errors: True
#   post_tasks:
#     - name: Copy Traefik Config File
#       template:
#         src: files/stack/traefik/traefik.toml
#         dest: /etc/traefik.toml
#     - name: Copy Traefik init script
#       template:
#         src: files/stack/traefik/traefik_debianinit.j2
#         dest: /etc/init.d/traefik
#         owner: root
#         group: root
#         mode: 0755
#   roles:
#        - { role: role-traefik, tags: ['docker', 'nomad', 'traefik'] }
#   vars:
#       traefik_bind_ip: "{{ ansible_lo['ipv4']['address'] }}"
