---
- hosts: stack
  gather_facts: true
  become: yes
  roles:
    - role: role-dns
    - role: role-docker
    - role: role-nomad
    - role: role-logrotate

- hosts: consuls
  become: true
  become_user: root
  roles:
      - role: role-consul

- hosts: vault
  gather_facts: true
  roles:
      - { role: role-vault, tags: ['vault'] }
