---
- hosts: docker_instances
  gather_facts: true
  become: yes
  roles:
    - role: role-dns
    - role: role-docker
    - role: role-nomad
    - role: role-logrotate

- hosts: consul_instances
  become: true
  become_user: root
  pre_tasks:
    - debug: msg="{{ consul_iface }}"
  roles:
    - role: role-consul

- hosts: vault_instances
  gather_facts: true
  become: true
  become_user: root
  roles:
    - role: role-vault

