---
# Required ansible collections
roles:
  # Github roles
  - name: role-users
    src: weareinteractive.users
  - name: role-basics
    src: ssh://git@github.com/loic-roux-404/role-basics.git
    version: "master"
    scm: git
  - name: role-dns
    src: ssh://git@github.com/mrlesmithjr/ansible-dnsmasq.git
    version: "master"
    scm: git
  - name: role-tools
    version: master
    src: ssh://git@github.com/loic-roux-404/role-tools.git
  - name: role-ledokku
    version: master
    src: ssh://git@github.com/loic-roux-404/role-ledokku.git
    scm: git
  - name: role-upgrade
    src: oefenweb.apt
  - name: role-shell
    version: master
    src: ssh://git@github.com/loic-roux-404/role-shell.git
    scm: git
  # External requirements
  - name: role-logrotate
    src: arillso.logrotate
  - name: role-firewall
    src: geerlingguy.firewall
  - name: role-sudo
    src: weareinteractive.sudo
    version: master
  # - name: role-docker
  #   src: nickjj.docker
  - name: role-dokku
    src: dokku_bot.ansible_dokku
    version: v2021.5.8
# replace zsh by role: gantsign.oh-my-zsh

collections:
  - name: community.general
  - name: community.docker
  - name: ansible.netcommon
  - name: ansible.posix
  - name: community.crypto
