# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = "{{ traefik_bind_ip }}:80"
    [entryPoints.traefik]
    address = "{{ traefik_bind_ip }}:8081"

logLevel = "INFO"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "consul"
watch = true

# Activate API and Dashboard
[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
