---
name: Vagrant box build
on: push # TODO on tag
jobs:
  debian:
    env:
      PACKER_VERSION: 1.6.5
      BOX_VERSION: 3.10.7
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        distrib:
          - VERSION: buster
            NAME: debian
            VAGRANT_CLOUD_TAG: loic-roux-404/deb64-buster

          - VERSION: focal
            NAME: ubuntu

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install moreutils
          sudo apt install -y unzip curl jq zsh
      - uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: ${{ env.PACKER_VERSION }}
      - name: Build image
        run: |
          cd debian && \
          VAGRANT_CLOUD_TOKEN=${{ secrets.VAGRANT_CLOUD_TOKEN }} make ${{ matrix.distrib.VERSION }}
